version: '3'

networks:
     homolog-network:
       driver: bridge

services:
    web:
        image: httpd:latest
        container_name: WebServer01
        restart: always
        networks:
            - homolog-network
        ports:
            - 8083:80
        volumes:
            - ./:/usr/local/apache2/htdocs/